OPCT-191: Removing OCP CI image dependency on build layer (#57)
Removing dependency on OCP CI registry images
(`registry.ci.openshift.org`) when building the project introduced on
https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/51
. It would be nice to unblock external contributors to use the tool when
need to build it locally.

We don't expect to fall into Docker limitations as that image should be
used in a developer environment.

https://issues.redhat.com/browse/OPCT-191

```
 $ make linux-amd64-container 
podman build -t quay.io/ocp-cert/opct:latest -f hack/Containerfile --build-arg=RELEASE_TAG=0.0.0 .
[1/2] STEP 1/5: FROM registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.13 AS builder
Trying to pull registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.13...
Error: error creating build container: initializing source docker://registry.ci.openshift.org/ocp/builder:rhel-8-golang-1.19-openshift-4.13: reading manifest rhel-8-golang-1.19-openshift-4.13 in registry.ci.openshift.org/ocp/builder: unauthorized: authentication required
make: *** [Makefile:49: linux-amd64-container] Error 125

```