OPCT-199: Fixes related to CI code static analysis on dependencies (#60)
The motivation of this PR is to fix/bump the static code check used on
Github CI, fixing issues reported on the new version. The issue has been
started, and it's isolated, from the PR
https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/54

Changes:

1) bump staticcheck version
2) fix issues reported by it

StaticCheck plugin used to Code Analysis on our CI was reporting issues
when bumping the OCP API lib, this is a false-positive:
-
https://github.com/redhat-openshift-ecosystem/provider-certification-tool/actions/runs/4608846263/jobs/8145167561

When updating the static check version it reports `io/ioutil`
deprecation addressed on this PR:

~~~
Error: internal/pkg/sippy/sippy.go:6:2: "io/ioutil" has been deprecated
since Go 1.16: As of Go 1.16, the same functionality is now provided by
package io or package os, and those implementations should be preferred
in new code. See the specific function documentation for details.
(SA1019)
Error: pkg/assets/bindata.go:11:2: "io/ioutil" has been deprecated since
Go 1.16: As of Go 1.16, the same functionality is now provided by
package io or package os, and those implementations should be preferred
in new code. See the specific function documentation for details.
(SA1019)
Error: Process completed with exit code 1.
~~~

Follow up for:
-
https://github.com/redhat-openshift-ecosystem/provider-certification-tool/pull/54
- https://issues.redhat.com/browse/OPCT-181

Tracking card: https://issues.redhat.com/browse/OPCT-199